USE ProgrammerDemoDb

SET IDENTITY_INSERT Courses OFF;
SET IDENTITY_INSERT Documentations OFF;
SET IDENTITY_INSERT [Events] OFF;
SET IDENTITY_INSERT Exams OFF;
SET IDENTITY_INSERT JobTasks OFF;
SET IDENTITY_INSERT Lectures OFF;
SET IDENTITY_INSERT RequiredSkills OFF;

--SET IDENTITY_INSERT [dbo].Documentations ON;

--INSERT INTO Documentations (Id, [Name], XpReward)
--VALUES (1, 'Data Structures - Documentation', 8),
--		(2, 'Algorithms - Documentation', 8),
--		(3, 'OOP - Documentation', 8),
--		(4, 'Testing - Documentation', 8),
--		(5, 'C# Tips And Tricks - Documentation', 8),
--		(6, 'Databases - Documentation', 8),
--		(7, 'EF Core - Documentation', 8),
--		(8, 'JS - Documentation', 8),
--		(9, 'Front-End Tricks - Documentation', 8),
--		(10, 'Asp.Net Core - Documentation', 8),
--		(11, 'ReactJs - Documentation', 8),
--		(12, 'Nodejs - Documentation', 8)

--SET IDENTITY_INSERT [dbo].Documentations OFF;
--SET IDENTITY_INSERT  [dbo].[Events] ON;

--INSERT INTO [Events] (Id, [Name], XpReward)
--VALUES (1, 'Data Structures - Event', 8),
--		(2, 'Algorithms - Event', 8),
--		(3, 'OOP - Event', 8),
--		(4, 'Testing - Event', 8),
--		(5, 'C# Tips And Tricks - Event', 8),
--		(6, 'Databases - Event', 8),
--		(7, 'EF Core - Event', 8),
--		(8, 'JS - Event', 8),
--		(9, 'Front-End Tricks - Event', 8),
--		(10, 'Asp.Net Core - Event', 8),
--		(11, 'ReactJs - Event', 8),
--		(12, 'Nodejs - Event', 8)

--SET IDENTITY_INSERT [dbo].[Events] OFF;
--SET IDENTITY_INSERT [dbo].AdditionalActivityCategories ON;

--INSERT INTO AdditionalActivityCategories (Id, [Name], HardSkillReward, SoftSkillReward, RequiredEnergy, DocumentationId, EventId)
--VALUES (1, 'Data Structures', 1, 2, 3, 1, 1),
--		(2, 'Algorithms', 1, 2, 3, 2, 2),
--		(3, 'OOP', 1, 2, 3, 3, 3),
--		(4, 'Testing', 1, 2, 3, 4, 4),
--		(5, 'C# Tips And Tricks', 1, 2, 3, 5, 5),
--		(6, 'Databases', 1, 2, 3, 6, 6),
--		(7, 'EF Core', 1, 2, 3, 7, 7),
--		(8, 'JS', 1, 2, 3, 8, 8),
--		(9, 'Front-End Tricks', 1, 2, 3, 9, 9),
--		(10, 'Asp.Net Core', 1, 2, 3, 10, 10),
--		(11, 'ReactJs', 1, 2, 3, 11, 11),
--		(12, 'Nodejs', 1, 2, 3, 12, 12)

--SET IDENTITY_INSERT [dbo].AdditionalActivityCategories OFF;
SET IDENTITY_INSERT [dbo].Courses ON;

INSERT INTO Courses (Id, [Name], Price, RequiredEnergy, HardSkillReward, SoftSkillReward, HardSkillName, SoftSkillName, XpReward)
VALUES (1, 'C# Fundamentals', 500, 5, 1, 1, 'CSharp', 'ProblemSolving', 10),
		(2, 'C# Advanced', 500, 5, 2.5, 1, 'CSharp', 'ProblemSolving', 15),
		(3, 'C# OOP', 500, 5, 1.5, 1, 'CSharp', 'ProblemSolving', 20),
		(4, 'Data Structures', 500, 5, 2.5, 1, 'DataStructures', 'AbstractThinking', 25),
		(5, 'Algorithms', 500, 5, 2.5, 1, 'Algorithms', 'ProblemSolving', 30),
		(6, 'Unit testing', 500, 5, 3, 1, 'Testing', 'AbstractThinking', 35),
		(7, 'Database Basics', 500, 5, 3, 1, 'DatabasesAndSQL', 'AbstractThinking', 40),
		(8, 'Ef Core', 500, 5, 3.5, 1, 'EfCore', 'ProblemSolving', 45),
		(9, 'JavaScript', 500, 5, 2, 1, 'VanillaJavaScript', 'ProblemSolving', 50),
		(10, 'HTML5', 500, 5, 2.5, 1, 'Html', 'Creativity', 55),
		(11, 'CSS3', 500, 5, 2.5, 1, 'Css', 'Creativity', 60),
		(12, 'ASP.Net Core', 500, 5, 2.5, 1, 'AspNetCore', 'AbstractThinking', 65),
		(13, 'ReactJs', 500, 5, 3.5, 1, 'React', 'Creativity', 70),
		(14, 'Nodejs', 500, 5, 4, 1, 'NodeJs', 'AbstractThinking', 75)

SET IDENTITY_INSERT [dbo].Courses OFF;
SET IDENTITY_INSERT [dbo].Exams ON;

INSERT INTO Exams (Id, RequiredEnergy, RequiredHardSkill, RequiredCodingSkill, CourseId)
VALUES (1, 10, 36, 18, 1),
		(2, 10, 86, 28, 2),
		(3, 10, 158, 52, 3),
		(4, 10, 110, 74, 4),
		(5, 10, 120, 98, 5),
		(6, 10, 108, 116, 6),
		(7, 10, 108, 132, 7),
		(8, 10, 140, 152, 8),
		(9, 10, 136, 186, 9),
		(10, 10, 130, 212, 10),
		(11, 10, 120, 236, 11),
		(12, 10, 112, 252, 12),
		(13, 10, 112, 266, 13)
		

SET IDENTITY_INSERT [dbo].Exams OFF;
SET IDENTITY_INSERT [dbo].Lectures ON;

INSERT INTO Lectures (Id, [Name], CourseId)
VALUES (1, 'Basic Syntax, Conditional Statements and Loops', 1),
		(2, 'Basic Syntax, Conditional Statements and Loops - Exercise', 1),
		(3, 'Data types and Variables', 1),
		(4, 'Data types and Variables - Exercise', 1),
		(5, 'Arrays', 1),
		(6, 'Arrays - Exercise', 1),
		(7, 'Methods', 1),
		(8, 'Methods - Exercise', 1),
		(9, 'Advanced Arrays', 1),
		(10, 'Advanced Arrays - Exercise', 1),
		(11, 'Objects and classes', 1),
		(12, 'Objects and classes - Exercise', 1),
		(13, 'Associative arrays', 1),
		(14, 'Associative arrays - Exercise', 1),
		(15, 'Text processing', 1),
		(16, 'Text processing - Exercise', 1),
		(17, 'Regular expressions', 1),
		(18, 'Regular expressions - Exercise', 1),
		(19, 'Stacks and Queues', 2),
		(20, 'Stacks and Queues - Exercise', 2),
		(21, 'Multidimensional arrays', 2),
		(22, 'Multidimensional arrays - Exercise', 2),
		(23, 'Associative arrays Advanced', 2),
		(24, 'Associative arrays Advanced - Exercise', 2),
		(25, 'Streams, files and directories', 2),
		(26, 'Streams, files and directories - Exercise', 2),
		(27, 'Functional programming', 2),
		(28, 'Functional programming - Exercise', 2),
		(29, 'Defining classes', 3),
		(30, 'Defining classes - Exercise', 3),
		(31, 'Generics', 3),
		(32, 'Generics - Exercise', 3),
		(33, 'Iterators and Comparators', 3),
		(34, 'Iterators and Comparators - Exercise', 3),
		(35, 'Working with abstraction', 3),
		(36, 'Working with abstraction - Exercise', 3),
		(37, 'Inheritance', 3),
		(38, 'Inheritance - Exercise', 3),
		(39, 'Encapsulation', 3),
		(40, 'Encapsulation - Exercise', 3),
		(41, 'Interfaces and Abstraction', 3),
		(42, 'Interfaces and Abstraction - Exercise', 3),
		(43, 'Polymorphism', 3),
		(44, 'Polymorphism - Exercise', 3),
		(45, 'SOLID', 3),
		(46, 'SOLID - Exercise', 3),
		(47, 'Reflection and Attributes', 3),
		(48, 'Reflection and Attributes - Exercise', 3),
		(49, 'Exception and Error hangling', 3),
		(50, 'Exception and Error hangling - Exercise', 3),
		(51, 'Design patterns', 3),
		(52, 'Design patterns - Exercise', 3),
		(53, 'Linear data structures - List and LinkedList', 4),
		(54, 'Linear data structures - List and LinkedList - Exercise', 4),
		(55, 'Linear data structures - Stacks And Queues', 4),
		(56, 'Linear data structures - Stacks And Queues - Exercise', 4),
		(57, 'Basic tree data structures - Tree, Binary tree', 4),
		(58, 'Basic tree data structures - Tree, Binary tree - Exercise', 4),
		(59, 'Binary Search trees', 4),
		(60, 'Binary Search trees - Exercise', 4),
		(61, 'Heaps and priority queue', 4),
		(62, 'Heaps and priority queue - Exercise', 4),
		(63, 'B-Trees and Red-Black trees', 4),
		(64, 'B-Trees and Red-Black trees - Exercise', 4),
		(65, 'AA-Trees and AVL trees', 4),
		(66, 'AA-Trees and AVL trees - Exercise', 4),
		(67, 'Rope and Trie', 4),
		(68, 'Rope and Trie - Exercise', 4),
		(69, 'Quad Trees, K-D Trees, Interval trees', 4),
		(70, 'Quad Trees, K-D Trees, Interval trees - Exercise', 4),
		(71, 'Hash tables', 4),
		(72, 'Hash tables - Exercise', 4),
		(73, 'Combining data structures', 4),
		(74, 'Combining data structures - Exercise', 4),
		(75, 'Recursion', 5),
		(76, 'Recursion - Exercise', 5),
		(77, 'Sorting Algorithms', 5),
		(78, 'Sorting Algorithms - Exercise', 5),
		(79, 'Searching Algorithms', 5),
		(80, 'Searching Algorithms - Exercise', 5),
		(81, 'Combinatorial Algorithms', 5),
		(82, 'Combinatorial Algorithms - Exercise', 5),
		(83, 'Greedy Algorithms', 5),
		(84, 'Greedy Algorithms - Exercise', 5),
		(85, 'Dynamic Programming', 5),
		(86, 'Dynamic Programming - Exercise', 5),
		(87, 'Dynamic Programming - Part 2', 5),
		(88, 'Dynamic Programming - Part 2 - Exercise', 5),
		(89, 'Graphs and Graphs Algorithms', 5),
		(90, 'Graphs and Graphs Algorithms - Exercise', 5),
		(91, 'Advanced Graphs and Graphs Algorithms - Part 1', 5),
		(92, 'Advanced Graphs and Graphs Algorithms - Part 1 - Exercise', 5),
		(93, 'Advanced Graphs and Graphs Algorithms - Part 2', 5),
		(94, 'Advanced Graphs and Graphs Algorithms - Part 2 - Exercise', 5),
		(95, 'Problem Solving Methodology', 5),
		(96, 'Problem Solving Methodology - Exercise', 5),
		(97, 'Solving Practical problems', 5),
		(98, 'Solving Practical problems - Exercise', 5),
		(99, 'Introduction to Unit testing', 6),
		(100, 'Introduction to Unit testing - Exercise', 6),
		(101, 'Fundamentals of Unit testing', 6),
		(102, 'Fundamentals of Unit testing - Exercise', 6),
		(103, 'Core unit testing techniques', 6),
		(104, 'Core unit testing techniques - Exercise', 6),
		(105, 'Breaking External dependencies', 6),
		(106, 'Breaking External dependencies - Exercise', 6),
		(107, 'Introduction to TDD', 6),
		(108, 'Introduction to TDD - Exercise', 6),
		(109, 'TDD in Action', 6),
		(110, 'TDD in Action - Exercise', 6),
		(111, 'Katas and TDD', 6),
		(112, 'Katas and TDD - Exercise', 6),
		(113, 'Writing Test Modules', 6),
		(114, 'Writing Test Modules - Exercise', 6),
		(115, 'Acceptance and Integration Tests', 6),
		(116, 'Acceptance and Integration Tests - Exercise', 6),
		(117, 'Database Introduction', 7),
		(118, 'Database Introduction - Exercise', 7),
		(119, 'Data Definition and Data types', 7),
		(120, 'Data Definition and Data types - Exercise', 7),
		(121, 'Basic CRUD', 7),
		(122, 'Basic CRUD - Exercise', 7),
		(123, 'Built-in functions', 7),
		(124, 'Built-in functions - Exercise', 7),
		(125, 'Data aggregation', 7),
		(126, 'Data aggregation - Exercise', 7),
		(127, 'Table relations', 7),
		(128, 'Table relations - Exercise', 7),
		(129, 'Subqueries and Joins', 7),
		(130, 'Subqueries and Joins - Exercise', 7),
		(131, 'Database Programmability', 7),
		(132, 'Database Programmability - Exercise', 7),
		(133, 'Triggers and Transactions', 7),
		(134, 'Triggers and Transactions - Exercise', 7),
		(135, 'Db Apps Introduction', 8),
		(136, 'Db Apps Introduction - Exercise', 8),
		(137, 'ORM Fundamentals', 8),
		(138, 'ORM Fundamentals - Exercise', 8),
		(139, 'Ef Core Introduction', 8),
		(140, 'Ef Core Introduction - Exercise', 8),
		(141, 'Code-First', 8),
		(142, 'Code-First - Exercise', 8),
		(143, 'Entity Relations', 8),
		(144, 'Entity Relations - Exercise', 8),
		(145, 'Advanced Querying', 8),
		(146, 'Advanced Querying - Exercise', 8),
		(147, 'C# Automapper', 8),
		(148, 'C# Automapper - Exercise', 8),
		(149, 'JSON Processing', 8),
		(150, 'JSON Processing - Exercise', 8),
		(151, 'XML Processing', 8),
		(152, 'XML Processing - Exercise', 8),
		(153, 'Best Practises and Architechture', 8),
		(154, 'Best Practises and Architechture - Exercise', 8),
		(155, 'Syntax, Funcions and Statements', 9),
		(156, 'Syntax, Funcions and Statements - Exercise', 9),
		(157, 'Objects', 9),
		(158, 'Objects - Exercise', 9),
		(159, 'Arrays', 9),
		(160, 'Arrays - Exercise', 9),
		(161, 'Advanced Functions', 9),
		(162, 'Advanced Functions - Exercise', 9),
		(163, 'DOM', 9),
		(164, 'DOM - Exercise', 9),
		(165, 'DOM Manipulations', 9),
		(166, 'DOM Manipulations - Exercise', 9),
		(167, 'Classes', 9),
		(168, 'Classes - Exercise', 9),
		(169, 'String and Regex', 9),
		(170, 'String and Regex - Exercise', 9),
		(171, 'This', 9),
		(172, 'This - Exercise', 9),
		(173, 'Object composition', 9),
		(174, 'Object composition - Exercise', 9),
		(175, 'Prototypes and Inheritance', 9),
		(176, 'Prototypes and Inheritance - Exercise', 9),
		(177, 'Rest services and AJAX', 9),
		(178, 'Rest services and AJAX - Exercise', 9),
		(179, 'Asynchronius programming', 9),
		(180, 'Asynchronius programming - Exercise', 9),
		(181, 'Templating', 9),
		(182, 'Templating - Exercise', 9),
		(183, 'Routing and Architechture', 9),
		(184, 'Routing and Architechture - Exercise', 9),
		(185, 'Single Page Application', 9),
		(186, 'Single Page Application - Exercise', 9),
		(187, 'WebPack', 9),
		(188, 'WebPack - Exercise', 9),
		(189, 'Introduction to HTML5', 10),
		(190, 'Introduction to HTML5 - Exercise', 10),
		(191, 'HTML Tags', 10),
		(192, 'HTML Tags - Exercise', 10),
		(193, 'HTML Structure', 10),
		(194, 'HTML Structure - Exercise', 10),
		(195, 'Semantic HTML', 10),
		(196, 'Semantic HTML - Exercise', 10),
		(197, 'HTML Advanced', 10),
		(198, 'HTML Advanced - Exercise', 10),
		(199, 'Introduction to CSS3', 11),
		(200, 'Introduction to CSS3 - Exercise', 11),
		(201, 'CSS and Typography', 11),
		(202, 'CSS and Typography - Exercise', 11),
		(203, 'CSS Box Model', 11),
		(204, 'CSS Box Model - Exercise', 11),
		(205, 'Position And Float', 11),
		(206, 'Position And Float - Exercise', 11),
		(207, 'FlexBox', 11),
		(208, 'FlexBox - Exercise', 11),
		(209, 'Media Queries', 11),
		(210, 'Media Queries - Exercise', 11),
		(211, 'Dev Workflows and Tools', 11),
		(212, 'Dev Workflows and Tools - Exercise', 11),
		(213, 'CSS variables and Icon fronts', 11),
		(214, 'CSS variables and Icon fronts - Exercise', 11),
		(215, 'CSS Transitions and Animations', 11),
		(216, 'CSS Transitions and Animations - Exercise', 11),
		(217, 'SASS', 11),
		(218, 'SASS - Exercise', 11),
		(219, 'CSS layout grid', 11),
		(220, 'CSS layout grid - Exercise', 11),
		(221, 'Building layouts', 11),
		(222, 'Building layouts - Exercise', 11),
		(223, 'AspNetCore Introduction', 12),
		(224, 'AspNetCore Introduction - Exercise', 12),
		(225, 'Razor Views', 12),
		(226, 'Razor Views - Exercise', 12),
		(227, 'Application Flow', 12),
		(228, 'Application Flow - Exercise', 12),
		(229, 'Filters and Middleware', 12),
		(230, 'Filters and Middleware - Exercise', 12),
		(231, 'Working with Data', 12),
		(232, 'Working with Data - Exercise', 12),
		(233, 'Web API', 12),
		(234, 'Web API - Exercise', 12),
		(235, 'Security and Identity', 12),
		(236, 'Security and Identity - Exercise', 12),
		(237, 'Project Architechture', 12),
		(238, 'Project Architechture - Exercise', 12),
		(239, 'Advaced Topics', 12),
		(240, 'Advaced Topics - Exercise', 12),
		(241, 'SignalR', 12),
		(242, 'SignalR - Exercise', 12),
		(243, 'Azure, Deployment and CI', 12),
		(244, 'Azure, Deployment and CI - Exercise', 12),
		(245, 'Blazor', 12),
		(246, 'Blazor - Exercise', 12),
		(247, 'Intro to ReactJs and JSX', 13),
		(248, 'Intro to ReactJs and JSX - Exercise', 13),
		(249, 'Components Fundamentals', 13),
		(250, 'Components Fundamentals - Exercise', 13),
		(251, 'Components Advanced', 13),
		(252, 'Components Advanced - Exercise', 13),
		(253, 'Routing', 13),
		(254, 'Routing - Exercise', 13),
		(255, 'Forms', 13),
		(256, 'Forms - Exercise', 13),
		(257, 'React Hooks', 13),
		(258, 'React Hooks - Exercise', 13),
		(259, 'Authentication', 13),
		(260, 'Authentication - Exercise', 13),
		(261, 'Advanced Techniques', 13),
		(262, 'Advanced Techniques - Exercise', 13),
		(263, 'Intro to Nodejs', 14),
		(264, 'Intro to Nodejs - Exercise', 14),
		(265, 'Nodejs Streams and Unitlities', 14),
		(266, 'Nodejs Streams and Unitlities - Exercise', 14),
		(267, 'ExpressJs and Templating', 14),
		(268, 'ExpressJs and Templating - Exercise', 14),
		(269, 'NoSQL', 14),
		(270, 'NoSQL - Exercise', 14),
		(271, 'Session and Authentication', 14),
		(272, 'Session and Authentication - Exercise', 14),
		(273, 'Validation and Error handling', 14),
		(274, 'Validation and Error handling - Exercise', 14),
		(275, 'Rest API', 14),
		(276, 'Rest API - Exercise', 14)

SET IDENTITY_INSERT [dbo].Lectures OFF;

